apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-website
  namespace: prod
  labels:
    name: devops-website
    instance: devops-website
data:
  DB_URL: "jdbc:mysql://mysqld.prod.svc.cluster.local:3306/devops"
  DB_USER: "devops"
  API_URL: "http://api.prod.svc.cluster.local:8080/api"
  API_USER: "apiuser"